### ISSUE TITLE
Dask labextension not working after upgrade 3.0.0 -> 4.0.1

### ISSUE THREAD

**Issue by rabernat** [dask/dask-labextension#166]
This is a cross post of https://github.com/pangeo-data/pangeo-docker-images/issues/177

**What happened**:

I pasted a link to a dask gateway cluster dashboard into the dask labextension dialog.

**What you expected to happen**:

I expected that it would work the same as it did in the past, allowing me to open the various windows of the dashboard in jupyterlab.

**Minimal Complete Verifiable Example**:

From jupyterlab
```python
from dask_gateway import Gateway
gateway = Gateway()
cluster = gateway.new_cluster()
display(cluster)
```

Then I copy/paste the dashboad link (for example: <https://hub.binder.pangeo.io/services/dask-gateway/clusters/prod.2103aa32d5a44956b54fe2f3919593b4/status>), into the labextension dialog. Nothing happens. The labextension never becomes active.

![image](https://user-images.githubusercontent.com/1197350/103908821-f17f3f00-50d0-11eb-9243-d804f5cda489.png)

**Anything else we need to know?**:

This works on earlier version of this environment which use dask-labextension 3.0.0.

There are no error messages on the javascript console specifically related to this. I did see these error messages, but I don't think they are related.

```
DevTools failed to load SourceMap: Could not load content for https://hub.binder.pangeo.io/user/pangeo-gallery-default-binder-u2qtxu7g/static/lab/main.cfb9280d54fcb641c354.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load SourceMap: Could not load content for https://hub.binder.pangeo.io/user/pangeo-gallery-default-binder-u2qtxu7g/static/lab/vendors~main.0d37c9e5f02fa65237ee.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
```

**Environment**:

A complete list of all packages in the environment is [here](https://github.com/pangeo-data/pangeo-docker-images/blob/c8c0d7271be0978518a1058330999dbb888b50d2/pangeo-notebook/packages.txt)

A binder that reproduces this problem can be found here:
https://binder.pangeo.io/v2/gh/pangeo-gallery/default-binder/64d772a/?urlpath=git-pull?repo=https://github.com/pangeo-gallery/physical-oceanography%26amp%3Burlpath=lab/tree/physical-oceanography/01_sea-surface-height.ipynb%3Fautodecode

- Dask version: 2.30.0
- Dask labextension: 4.0.1
- jupyter-server-proxy: 1.5.2
- Python version: 3.8
- Operating System: Linux
- Install method (conda, pip, source): Conda

**Comment by ian-r-rose** [comment]
Thanks to the investigations of @TomAugspurger, this should be fixed (and published as 5.0.1). Things seem to work in my testing, but please let me know if you find that to not be the case

**Comment by scottyhq** [comment]
@ian-r-rose @TomAugspurger I've confirmed the new version works for binderhubs (https://aws-uswest2-binder.pangeo.io/v2/gh/scottyhq/pageodev-binder-image/master?urlpath=lab) using a new docker image with dask-labextension 5.0.1 (pangeo/pangeo-notebook:aeffb56) 

But I'm still unable to get an active labextension on jupyterhub. I noticed that copying the full https:// dashboard URL into the dashboard in jupyterhub seems to automatically truncate it to `/services/dask-gateway/clusters/...` and then i see a bunch of errors in the javascript console like:

<img width="1720" alt="Screen Shot 2021-03-03 at 9 11 30 AM" src="https://user-images.githubusercontent.com/3924836/109844005-8baac180-7c00-11eb-9799-140c325ed6b2.png">

 i think you all have access to https://staging.aws-uswest2.pangeo.io (staging pangeo notebook) if you want to try things out.

**Comment by ian-r-rose** [comment]
Thanks for the update @scottyhq. It appears that I don't have access to the staging jupyterhub, do you have the power to add me?

**Comment by scottyhq** [comment]
> Thanks for the update @scottyhq. It appears that I don't have access to the staging jupyterhub, do you have the power to add me?

just added you. signup form also available here https://pangeo.io/cloud.html#sign-up

**Comment by scottyhq** [comment]
@ian-r-rose @TomAugspurger should this be re-opened? I think #167 fixed binderhubs but not jupyterhub+dask-gateway? you'd think both would work, but i guess there is enough difference in how the two are configured... if it's more of an issue with how the jupyterhub is configured, maybe we need a separate issue over in https://github.com/pangeo-data/pangeo-cloud-federation
